language: python

python: 3.7

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

install:
  - "pip install -U pip"
  - "pip install unidecode"
  - "pip install lektor"

script:
  - "lektor build"

deploy:
  - provider: script
    script: "lektor deploy production"
    on:
       branch: production