import React from 'react';
import Head from 'next/head';
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Button variant="contained">Hello World</Button>
        </div>
      </main>
    </>
  );
}
