name: Staging Checks

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /arendondiosa.github.io
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.x
      - name: Install packages
        run: npm install
      - name: Build project
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
  format-js:
    name: JS Code Format
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: rendon-co
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.17"
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-14.17-${{ hashFiles('rendon-co/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-14.17-${{ hashFiles('rendon-co/package.json') }}
      - name: Install node dependencies
        run: |
          cd rendon-co/
          npm install
      - name: Show node environment
        run: |
          node --version
          npm --version
      - name: Run JS lint
        run: |
          cd rendon-co/
          npm run lint-only
  format-css:
    name: CSS Code Format
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: rendon-co
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.17"
      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-14.17-${{ hashFiles('rendon-co/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-14.17-${{ hashFiles('rendon-co/package.json') }}
      - name: Install node dependencies
        run: |
          cd rendon-co/
          npm install stylelint stylelint-config-standard
      - name: Show node environment
        run: |
          node --version
          npm --version
      - name: Run JS lint
        run: |
          cd rendon-co/
          npm run style-lint
